---
- name: try to install a package
  hosts: plesk.yhoro.de
#Die Variablen entweder als eine Liste in packages_list als variable
#oder als ein string in packages als variable zB packages: "vim,haha"
#Die variablen können dann per Host in den host_vars definiert werden oder direkt hier
#Die rolle Prüft erstens ob einer der Pakete schon vorinstalliert ist und benachrichtigt
#Sie am ende welche Version genau schon auf dem Zielsystem installiert ist
#danach fängt die Rolle an nur mit einem update der apt repo in dem fall und installiert die
#Packete die nicht vorinstalliert ist
#Am Ende werden Sie benachrichtigt welche Pakete und welche Version erfolgreich
#installiert wurden
# Über fehlerhal
  vars:
    #packages: "vim,haha"
    packages_list:
      #- vim
      #- haha
      #- bash-completion
      #- nano
      #- test
      - net-tools
      #- php8.0
  roles:
    - apache2
    - apt_install
